<a href="https://colab.research.google.com/github/OketchOdanga/DataAnalysisWithPython/blob/main/DataAnalysisWithPython(FreeCodecamp).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [31]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### Dimesions and Shapes

In [ ]:
A = np.array([[1,3,4],[5,7,9]])
A

array([[1, 3, 4],
       [5, 7, 9]])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [[2,3,4],[5,6,7]],
     [[8,9,0],[7,1,3]]
    ])
B

array([[[2, 3, 4],
        [5, 6, 7]],

       [[8, 9, 0],
        [7, 1, 3]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
A[1]

array([5, 7, 9])

In [ ]:
A[0]

array([1, 3, 4])

In [ ]:
#(x,y)
A[1][0]# element in the second row first column.

5

###Analysis

In [ ]:
A.mean()

4.833333333333333

In [ ]:
B.mean()

4.583333333333333

In [ ]:
AB = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])
AB

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [ ]:
print(AB[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


### Broadcasting and Vectorized operations

In [28]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a += 100
a

array([200, 201, 202, 203])

In [33]:
b = np.arange(5)
b + 20

array([20, 21, 22, 23, 24])

###Boolean Arrays

In [36]:
a >= 202

array([False, False,  True,  True])

In [37]:
a[a>=202]

array([202, 203])

In [38]:
a.mean()

201.5

In [39]:
a[a>a.mean()] # values greater than the mean(201.5)

array([202, 203])

In [41]:
a[~(a>a.mean())] # values not greater than the mean(201.5)

array([200, 201])

In [42]:
C = np.random.randint(100, size = (3,3))

In [43]:
C

array([[77,  2, 10],
       [36,  7, 27],
       [54, 35, 81]])

In [44]:
C > 30

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

####Exercise

In [45]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]
