<a href="https://colab.research.google.com/github/OketchOdanga/DataAnalysisWithPython/blob/main/DataAnalysisWithPython(FreeCodecamp).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [31]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### Dimesions and Shapes

In [ ]:
A = np.array([[1,3,4],[5,7,9]])
A

array([[1, 3, 4],
       [5, 7, 9]])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [[2,3,4],[5,6,7]],
     [[8,9,0],[7,1,3]]
    ])
B

array([[[2, 3, 4],
        [5, 6, 7]],

       [[8, 9, 0],
        [7, 1, 3]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
A[1]

array([5, 7, 9])

In [ ]:
A[0]

array([1, 3, 4])

In [ ]:
#(x,y)
A[1][0]# element in the second row first column.

5

###Analysis

In [ ]:
A.mean()

4.833333333333333

In [ ]:
B.mean()

4.583333333333333

In [ ]:
AB = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])
AB

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [ ]:
print(AB[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


### Broadcasting and Vectorized operations

In [28]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a += 100
a

array([200, 201, 202, 203])

In [33]:
b = np.arange(5)
b + 20

array([20, 21, 22, 23, 24])

###Boolean Arrays

In [36]:
a >= 202

array([False, False,  True,  True])

In [37]:
a[a>=202]

array([202, 203])

In [38]:
a.mean()

201.5

In [39]:
a[a>a.mean()] # values greater than the mean(201.5)

array([202, 203])

In [41]:
a[~(a>a.mean())] # values not greater than the mean(201.5)

array([200, 201])

In [42]:
C = np.random.randint(100, size = (3,3))

In [43]:
C

array([[77,  2, 10],
       [36,  7, 27],
       [54, 35, 81]])

In [44]:
C > 30

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

####Exercise

In [45]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


##Pandas

In [1]:
import pandas as pd
import numpy as np

###pandas series

In [3]:
#G7 population analysis
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [4]:
g7_pop.name = "G7 population in millions"

In [5]:
g7_pop.dtype

dtype('float64')

In [6]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [7]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [8]:
g7_pop.index = ["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"]

In [9]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

QUIZ

In [10]:
certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


In [11]:
certificates_earned

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64

###Pandas indexing

In [12]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [13]:
g7_pop['Canada']

35.467

using iloc attribute to do numeric postioning/ sequencial selection

In [16]:
g7_pop.iloc[0] #checking the population of canada which is the first item in the series.

35.467

selecting multiple elemennts once

In [21]:
g7_pop[['Italy', 'France']]

Italy     60.665
France    63.951
Name: G7 population in millions, dtype: float64

In [20]:
g7_pop.iloc[[0,1]]

Canada    35.467
France    63.951
Name: G7 population in millions, dtype: float64

###condtional selection (boolean array)

In [22]:
g7_pop > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 population in millions, dtype: bool

In [24]:
g7_pop[g7_pop > 70]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [26]:
g7_pop[(g7_pop > 70) & (g7_pop > 90)]

Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

###Modifying series

In [27]:
g7_pop['Canada'] = 78.9

In [28]:
g7_pop.iloc[-1] = 318.98 # modifying the country in the last position

In [29]:
g7_pop

Canada             78.900
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.980
Name: G7 population in millions, dtype: float64

QUIZ

In [30]:
certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64
