<a href="https://colab.research.google.com/github/OketchOdanga/DataAnalysisWithPython/blob/main/DataAnalysisWithPython(FreeCodecamp).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### Dimesions and Shapes

In [ ]:
A = np.array([[1,3,4],[5,7,9]])
A

array([[1, 3, 4],
       [5, 7, 9]])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [[2,3,4],[5,6,7]],
     [[8,9,0],[7,1,3]]
    ])
B

array([[[2, 3, 4],
        [5, 6, 7]],

       [[8, 9, 0],
        [7, 1, 3]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
A[1]

array([5, 7, 9])

In [ ]:
A[0]

array([1, 3, 4])

In [ ]:
#(x,y)
A[1][0]# element in the second row first column.

5

###Analysis

In [ ]:
A.mean()

4.833333333333333

In [ ]:
B.mean()

4.583333333333333

In [ ]:
AB = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])
AB

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [ ]:
print(AB[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


### Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a += 100
a

array([200, 201, 202, 203])

In [ ]:
b = np.arange(5)
b + 20

array([20, 21, 22, 23, 24])

###Boolean Arrays

In [ ]:
a >= 202

array([False, False,  True,  True])

In [ ]:
a[a>=202]

array([202, 203])

In [ ]:
a.mean()

201.5

In [ ]:
a[a>a.mean()] # values greater than the mean(201.5)

array([202, 203])

In [ ]:
a[~(a>a.mean())] # values not greater than the mean(201.5)

array([200, 201])

In [ ]:
C = np.random.randint(100, size = (3,3))

In [ ]:
C

array([[77,  2, 10],
       [36,  7, 27],
       [54, 35, 81]])

In [ ]:
C > 30

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

####Exercise

In [ ]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


##Pandas

In [2]:
import pandas as pd
import numpy as np

###pandas series

In [ ]:
#G7 population analysis
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [ ]:
g7_pop.name = "G7 population in millions"

In [ ]:
g7_pop.dtype

dtype('float64')

In [ ]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [ ]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
g7_pop.index = ["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"]

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

QUIZ

In [ ]:
certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


In [ ]:
certificates_earned

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64

###Pandas indexing

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [ ]:
g7_pop['Canada']

35.467

using iloc attribute to do numeric postioning/ sequencial selection

In [ ]:
g7_pop.iloc[0] #checking the population of canada which is the first item in the series.

35.467

selecting multiple elemennts once

In [ ]:
g7_pop[['Italy', 'France']]

Italy     60.665
France    63.951
Name: G7 population in millions, dtype: float64

In [ ]:
g7_pop.iloc[[0,1]]

Canada    35.467
France    63.951
Name: G7 population in millions, dtype: float64

###condtional selection (boolean array)

In [ ]:
g7_pop > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 population in millions, dtype: bool

In [ ]:
g7_pop[g7_pop > 70]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

In [ ]:
g7_pop[(g7_pop > 70) & (g7_pop > 90)]

Japan            127.061
United States    318.523
Name: G7 population in millions, dtype: float64

###Modifying series

In [ ]:
g7_pop['Canada'] = 78.9

In [ ]:
g7_pop.iloc[-1] = 318.98 # modifying the country in the last position

In [ ]:
g7_pop

Canada             78.900
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.980
Name: G7 population in millions, dtype: float64

QUIZ

In [ ]:
certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


### Pandas Dataframe

In [3]:
# Creating the DataFrame
data = {
    "Population": [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    "GDP": [1785387.00, 2833687.00, 3874437.00, 2167744.00, 4602367.00, 2950039.00, 17348075.00],
    "Surface": [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
    "HDI": [0.913, 0.888, 0.916, 0.873, 0.891, 0.907, 0.915],
    "Continent": ["America", "Europe", "Europe", "Europe", "Asia", "Europe", "America"]
}

# Defining country names as the index
index = ["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"]

df = pd.DataFrame(data, index=index)

# Display the DataFrame
print(df)

                Population         GDP  Surface    HDI Continent
Canada              35.467   1785387.0  9984670  0.913   America
France              63.951   2833687.0   640679  0.888    Europe
Germany             80.940   3874437.0   357114  0.916    Europe
Italy               60.665   2167744.0   301336  0.873    Europe
Japan              127.061   4602367.0   377930  0.891      Asia
United Kingdom      64.511   2950039.0   242495  0.907    Europe
United States      318.523  17348075.0  9525067  0.915   America


In [4]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [5]:
df.size

35

In [6]:
df.shape

(7, 5)

In [7]:
df.describe()

Population           GDP       Surface       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Population  7 non-null      float64
 1   GDP         7 non-null      float64
 2   Surface     7 non-null      int64  
 3   HDI         7 non-null      float64
 4   Continent   7 non-null      object 
dtypes: float64(3), int64(1), object(1)
memory usage: 636.0+ bytes


#### indexing and slicing dataframes

In [10]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

selection using index

In [11]:
df.loc['Canada']

Population       35.467
GDP           1785387.0
Surface         9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

selecting rows by sequential positions

In [12]:
df.iloc[0]

Population       35.467
GDP           1785387.0
Surface         9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [15]:
df.iloc[[0,1,-1]]

Population         GDP  Surface    HDI Continent
Canada             35.467   1785387.0  9984670  0.913   America
France             63.951   2833687.0   640679  0.888    Europe
United States     318.523  17348075.0  9525067  0.915   America

In [16]:
df.iloc[1:3]

Population        GDP  Surface    HDI Continent
France       63.951  2833687.0   640679  0.888    Europe
Germany      80.940  3874437.0   357114  0.916    Europe

In [18]:
df.iloc[1:3, 3] #checking the contents of column 3 in row 2 and 3

France     0.888
Germany    0.916
Name: HDI, dtype: float64

QUIZ

In [19]:
certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


###Conditional selection and Modifying Dataframes

In [20]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [21]:
df[df['Population'] > 70]

Population         GDP  Surface    HDI Continent
Germany            80.940   3874437.0   357114  0.916    Europe
Japan             127.061   4602367.0   377930  0.891      Asia
United States     318.523  17348075.0  9525067  0.915   America

In [22]:
df.loc[df['Population'] > 70]

Population         GDP  Surface    HDI Continent
Germany            80.940   3874437.0   357114  0.916    Europe
Japan             127.061   4602367.0   377930  0.891      Asia
United States     318.523  17348075.0  9525067  0.915   America

In [23]:
langs = pd.Series(['French', 'Italian', 'English', 'German'],
                  index = ['France', 'Italy', 'United Kingdom', 'Germany'],
                  name = 'Language')

In [24]:
# adding the language column to the dataframe
df['Language'] = langs

In [25]:
df

Population         GDP  Surface    HDI Continent Language
Canada              35.467   1785387.0  9984670  0.913   America      NaN
France              63.951   2833687.0   640679  0.888    Europe   French
Germany             80.940   3874437.0   357114  0.916    Europe   German
Italy               60.665   2167744.0   301336  0.873    Europe  Italian
Japan              127.061   4602367.0   377930  0.891      Asia      NaN
United Kingdom      64.511   2950039.0   242495  0.907    Europe  English
United States      318.523  17348075.0  9525067  0.915   America      NaN

Replacing values per column

In [26]:
df['Language'] = 'English'

In [27]:
df

Population         GDP  Surface    HDI Continent Language
Canada              35.467   1785387.0  9984670  0.913   America  English
France              63.951   2833687.0   640679  0.888    Europe  English
Germany             80.940   3874437.0   357114  0.916    Europe  English
Italy               60.665   2167744.0   301336  0.873    Europe  English
Japan              127.061   4602367.0   377930  0.891      Asia  English
United Kingdom      64.511   2950039.0   242495  0.907    Europe  English
United States      318.523  17348075.0  9525067  0.915   America  English

Renaming columns

In [28]:
df.rename(
    columns = {
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index= {
        'United States': 'USA',
        'United Kingdom': 'UK'
    }
)

Population         GDP  Surface  Human Development Index Continent  \
Canada       35.467   1785387.0  9984670                    0.913   America   
France       63.951   2833687.0   640679                    0.888    Europe   
Germany      80.940   3874437.0   357114                    0.916    Europe   
Italy        60.665   2167744.0   301336                    0.873    Europe   
Japan       127.061   4602367.0   377930                    0.891      Asia   
UK           64.511   2950039.0   242495                    0.907    Europe   
USA         318.523  17348075.0  9525067                    0.915   America   

        Language  
Canada   English  
France   English  
Germany  English  
Italy    English  
Japan    English  
UK       English  
USA      English

QUIZ

In [29]:
certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
longest_streak = pd.Series([13, 11, 9, 7], index=names)
certificates_earned['Longest streak'] = longest_streak

print(certificates_earned)

       Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7
